### ISSUE TITLE
__init__() got an unexpected keyword argument 'baudrate'

### ISSUE THREAD

**Issue by mikebzh44** [demikl/python-teleinfo#6]
Bonjour.

Je tente d'installer et d'utiliser votre librairie pour interroger mon compteur Linky qui est passé en mode Standard suite à l'installation de mes panneaux solaires. Mon montage utilise un opto-coupleur sur une breadboard qui marchait très bien en mode TIC Historique via un programme écrit en C que j'avais récupéré sur le site hallard.me : 

```
/* ======================================================================
Program : teleinfo
Version : 1.0.8
Purpose : send/recevice teleinformation from severals devices then can
          - write to MySql
          - write to Emoncms
          - send UDP frame over network

Author  : (c) Charles-Henri Hallard
          http://hallard.me
Comments: some code grabbed from picocom and other from teleinfo
  : You can use or distribute this code unless you leave this comment
  : too see this code correctly indented, please use Tab values of 2
  06/09/2013 : Added EMONCMS feature
  12/09/2013 : Added Linked List for only post real time changed values
  30/03/2014 : Added Emoncms real time post (only changed values)
  15/04/2014 : Added configuration parameters with also config file
====================================================================== */

```

Je suis parti sur un Raspberry vierge et la dernière Raspbian.

J'ai installé votre librairie via : pip install teleinfo

J'utilise le petit script : 

```
#!/usr/bin/python
from teleinfo import Parser
from teleinfo.hw_vendors import PITInfo
ti = Parser(PITInfo(baudrate=9600))
print ti.get_frame()
```

Mais quand je l'exécute, j'ai l'erreur suivante : 

```
Traceback (most recent call last):
  File "./PITinfo.py", line 4, in <module>
    ti = Parser(PITInfo(baudrate=9600))
  File "/home/pi/.local/lib/python2.7/site-packages/teleinfo/hw_vendors.py", line 64, in __init__
    super(PITInfo, self).__init__(port, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'baudrate'
```

Est-ce normal ? Ai-je loupé quelque chose ?

Merci.

**Comment by mikebzh44** [comment]
Bon, en modifiant dans le code du hw_vendors à 9600 et en appliquant les modifications de ce ticket : 

https://github.com/demikl/python-teleinfo/issues/5

Je peux lire la trame TIC maintenant : 

```
pi@raspberrypi:~ $ ./PITinfo.py
{'EASD01': '003998465', 'STGE': '003A4501', 'EASD03': '000000000', 'EASD02': '004388589', 'EASD04': '000000000', 'IRMS1': '015', 'PJOURF+1': '0000C001 07248002 2324C001 NONUTILE NONUTILE NONUTILE NONUTILE NONUTILE NONUTILE NONUTILE NONUTILE', 'NJOURF': '00', 'EASF03': '000000000', 'EASF02': '004388589', 'EASF01': '003998465', 'EASF07': '000000000', 'ADSC': '061961603260', 'EASF05': '000000000', 'EASF04': '000000000', 'DATE': ('H210206101626', ''), 'EASF09': '000000000', 'EASF08': '000000000', 'LTARF': 'HEURE  PLEINE', 'CCASN': ('H210206100000', '01212'), 'ERQ4': '003223226', 'ERQ2': '000000000', 'ERQ3': '000001864', 'ERQ1': '000005748', 'PRM': '14275687320408', 'NTARF': '02', 'SMAXSN': ('H210206010137', '04361'), 'CCASN-1': ('H210206093000', '01356'), 'SINSTS': '03455', 'EAST': '008387054', 'UMOY1': ('H210206101000', '231'), 'RELAIS': '000', 'SINSTI': '00000', 'PCOUP': '09', 'URMS1': '232', 'EASF10': '000000000', 'SMAXIN-1': ('H210205135848', '00463'), 'MSG1': 'PAS DE          MESSAGE', 'NJOURF+1': '00', 'NGTF': 'H PLEINE/CREUSE', 'SMAXIN': ('H210206000000', '00000'), 'VTIC': '02', 'SMAXSN-1': ('H210205003219', '04335'), 'PREF': '09', 'EAIT': '000000722', 'EASF06': '000000000'}
```

**Comment by mikebzh44** [comment]
Par contre, petit soucis, le programme Python ne rend jamais la main.

Obligé de faire CTRL+C dans la console

J'ai essayé avec des quit(), exit(), sys.exit()

Rien ne marche.
